getting Weather data
andym80/react-capstone pull request #1
Opened 2022-09-17 23:55 UTC by andym80

Get current weather information by cities, with an input search Filtered information by Temperature max  and min, present weather icon and humidity.

2022-09-18 00:09 UTC, addod19 reviewed
### Hi @andym80, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because it is lacking a descriptive README file. Here is the [template guide](https://github.com/microverseinc/readme-template/blob/master/README.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-18 01:43 UTC, danielufeli requested changes
Hi @andym80 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-18 01:43 UTC, danielufeli commented on README.md
> +- This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app), using the [Redux](https://redux.js.org/) and [Redux Toolkit](https://redux-toolkit.js.org/) temp
- [ ] Nice working on your Readme, kindly add appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/). should

2022-09-18 01:43 UTC, danielufeli commented on README.md
> +
- [ ] Nice Working on your project, kindly add a link to the live version of your project using Heroku, Netlify, or GitHub Pages.
- [ ] Kindly add a 5mins recorded video presenting the features of the project.

2022-09-18 01:43 UTC, danielufeli commented on src/components/WeatherPanel.js
> +  let urlWeather = 'https://api.openweathermap.org/data/2.5/weather?&appid=56cdd6a9ec3b0492107abe99f711937a&lang=EN';
- [ ] Nice working on your components, kindly check I get the below errors when I try to search or load the project.

![error---](https://user-images.githubusercontent.com/48371156/190881905-e2e6f502-0b95-4291-b178-143cd0391f2a.png)

2022-09-18 01:43 UTC, danielufeli commented on src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
- [ ] Nice testing your components, kindly check all tests are currently failing, see screenshot below.

![test---](https://user-images.githubusercontent.com/48371156/190881984-cd17ef97-a7fa-4dcb-80fc-6946efd6574e.png)

2022-09-18 04:24 UTC, whiz25 requested changes
Hi @andym80, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🎉 🎉 🎉 
- Nice work making changes suggested

## Required Changes ♻️
_Check the comments under the review._
- Add credit to the designer
- Add a live link to the deployed app
- You still have failing tests. Please fix those

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 14:04 UTC, dasileker requested changes
### **Hi @andym80,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**

- Linters are passing ✅.
- Codes are really clean 👌.
- PR is well made.


## Required Changes ♻️
_Check the comments under the review._

- **Hello and excellent job on the app but you didn't add the deployed link to your readme file also as you did deploy in Heroku please remove the deployment from netlify and if you still want to deploy on netlify you have two `console.log` in `WeatherPanel.js` is causing you issues while deploying remove theme.**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 16:06 UTC, ShahierNashaat approved these changes
Hi @andym80, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 16:11 UTC, merged